name: Package Size Report

on:
  pull_request:
    branches: [main] # ⬅ Add other branches you want size checks on

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12" # ⬅ Specify a version of Node.js to build your app

      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.0.1
        with:
          # Version of PNPM to install
          version: 6.17.2
          # Where to store PNPM files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: pnpm install # optional, default is null

      - name: Package size report
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
